### ISSUE TITLE
Incorrect results with `absorb`?

### ISSUE THREAD

**Issue by mcaceresb** [sergiocorreia/ivreghdfe#13]
I'd assume this is an issue stemming from ftools or reghdfe, since this repo hasn't changed in some time. But I am not sure what part of it is causing this issue. In any case, the results form an IV with `absorb` are wrong:

```stata
local sergio https://raw.githubusercontent.com/sergiocorreia

cap ado uninstall reghdfe
cap ado uninstall ftools
cap ado uninstall ivreghdfe

net install reghdfe, from(`sergio'/reghdfe/master/src/) replace
net install ftools,  from(`sergio'/ftools/master/src/)  replace

reghdfe, compile
ftools,  compile

ssc install ivreg2
net install ivreghdfe, from(`sergio'/ivreghdfe/master/src/) replace

sysuse auto, clear
xi: ivreghdfe price (mpg = foreign) i.rep78
xi: ivreg     price (mpg = foreign) i.rep78
xi: ivreghdfe price (mpg = foreign), absorb(rep78)
```

The first two give the exact same coefficient, 10.335, but the third gives 0.0208.

**Comment by sergiocorreia** [comment]
I think I know the problem. Yesterday I changed the reghdfe code to keep by default the variables standardized after reghdfe (it improve numerical accuracy). 

The fix should be relatively simple (changing an argument in the call to partial_out()) but we are swamped with recruiting this week so I'm only going to be able to update it tomorrow evening,. at the earliest.

(on the meantime, You can use reghdfe with the old option to run the IV though)

**Comment by sergiocorreia** [comment]
Actually, a better soln osnto change the reghdfe code so it does not returned standardized values by default. There might be other programs out there using the internals of reghdfe that might get affected otherwise

**Comment by mcaceresb** [comment]
i just tested the release from the 27th and it works fine, but the release from the 28th introduces the problem (reghdfe).

What is the old option to run the IV? No idea this was a thing.

**Comment by sergiocorreia** [comment]
Makes sense; I'll work on a patch asap tomorrow evening

About old, you can add -old- to the options, and it will run reghdfe
version 3, which supported IV regressions directly.

**Comment by sergiocorreia** [comment]
Just pushed a commit to reghdfe that should fix this issue. Let me know if it works on your side.

(BTW, you don't need to use the `xi:` prefix anymore, as both ivreg2 and reghdfe support factor variables! see `help xi` for more details)

**Comment by mcaceresb** [comment]
Yup, looking good now!

PS: `xi` was there bc `ivreg` didn't support factor variables and my mind really disliked the code alignment otherwise. I mean, the third regression didn't even use factor variables and I still put a `xi` in front.
