### ISSUE TITLE
R(3499) with IV/2sls using reghdfe, old and ivreghdfe

### ISSUE THREAD

**Issue by ItsMatthias** [sergiocorreia/ivreghdfe#19]
Dear Sergio, 

Many thanks for providing the commands reghdfe and ivreghdfe. I use them extensively, given my old syntax I still prefer the reghdfe, old for running 2sls. 
Since today I face a new error message I never say before and I do not know what to do: 

.  reghdfe  kse_ef60 ( kse_ef61 = kse_ef53), absorb (jahr)  old
(running historical version of reghdfe)
            assert_msg():  3499  _assert_abort() not found
map_init_keepsingletons():     -  function returned error
                 <istmt>:     -  function returned error
r(3499);

.  ivreghdfe  kse_ef60 ( kse_ef61 = kse_ef53), absorb (jahr)
            assert_msg():  3499  _assert_abort() not found
         fixed_effects():     -  function returned error
                 <istmt>:     -  function returned error
r(3499);

I ran the exact same code on the exact same data multiple times already and I never faced this error message. The data is also rather small and simple. Since I work at an institute where our computers share the same ado-folder, it could very well be the case that someone has updated reghdfe and that this introduced this problem. 

Do you know of this issue? It would be of great help to me if you could point out what I did potentially wrong (or is this a new bug?). 

Many thanks for all your work,
bests, 
matthias

**Comment by ItsMatthias** [comment]
reghdfe, compile solved

**Comment by sergiocorreia** [comment]
Great to hear that! It seems that the SSC version of reghdfe is not compiling by default, which creates problems.
