### ISSUE TITLE
FE in first stage of ivreghdfe?

### ISSUE THREAD

**Issue by fedehuneeus** [sergiocorreia/ivreghdfe#26]
Hi Sergio, Wanted to double check whether the first stage of ivreghdfe includes the same absorb() variables from the second stage, ie, same included instruments. Couldn't find this from the output in stata, also didn't find the option in the help of the command. Thanks!

**Comment by sergiocorreia** [comment]
It does. Since ivreghdfe is almost the same as ivreg2, you can verify by e.g. running ivreg2 with the first option and reghdfe on the first stage:

```stata
sysuse auto
ivreghdfe price weight (length=gear) , a(turn) first
reghdfe length gear weight, a(turn)
```

**Comment by fedehuneeus** [comment]
Awesome. Thanks!
