### ISSUE TITLE
command reghdfe_store_alphas is unrecognized

### ISSUE THREAD

**Issue by MiGitMa** [sergiocorreia/ivreghdfe#29]
Hi, 

I am using  ivreghdfe and would like to save fixed effects or the residuals with  

ivreghdfe price weight, absorb(fe=trunk)
ivreghdfe price weight, absorb(trunk, resid(myresidname))

In either case, I obtain the error message: 

``command reghdfe_store_alphas is unrecognized".
Doing the same with reghdfe works fine. 

I tried to follow all steps of an earlier post (https://github.com/sergiocorreia/reghdfe/issues/148) and should have the latest versions installed (see below).

Do you know what could cause the problem? 
I would be really grateful for any suggestions on how to fix it.

Best
M

which ivreghdfe
...Library/Application Support/Stata/ado/plus/i/ivreghdfe.ado
*! ivreghdfe 1.0.1  05may2020
*! this just adds absorb() to this code:
*! ivreg2 4.1.10  9Feb2016
*! authors cfb & mes
*! see end of file for version comments

. which reghdfe
...Library/Application Support/Stata/ado/plus/r/reghdfe.ado
*! version 5.8.0 27dec2019

**Comment by matthew-lee** [comment]
I have had an identical issue: saving fixed effects works fine for reghdfe, but not for ivreghdfe. Like MiGitMa I have uninstalled and re-installed all of the most recent versions.

**Comment by sergiocorreia** [comment]
A [while ago](https://github.com/sergiocorreia/reghdfe/commit/68eaceb897c40fd519e96e24f0545adb4334acb9) I moved reghdfe_store_alphas.ado into reghdfe.ado itself, which removed the need for `reghdfe, compile` after installing reghdfe.

However, as both of you experienced, this created a problem with ivreghdfe. It took me a while to find out how to fix this problem, but after much thinking and many cups of coffee, [this bugfix](https://github.com/sergiocorreia/ivreghdfe/commit/2c154b70c7c304fd47a664556013e554331d4a92) should do it. Of course, with ado files so long, even small fixes are tricky so let me know if it still doesn't work on your side

Cheers,
S

**Comment by matthew-lee** [comment]
Brilliant, just tested and it worked. Thanks, Sergio - I'm grateful for your terrific code and I hope I'll have a chance to buy you a coffee someday.
