### ISSUE TITLE
issues with clustering - insufficient observations

### ISSUE THREAD

**Issue by nikhilklath** [sergiocorreia/ivreghdfe#36]
@sergiocorreia , I needed some advice on clustering while using ivreghdfe. 

My code is -
`ivreghdfe yvar (ever_win = true_treat), absorb(strata gender#batch city#batch yrs_school#batch age#batch mult_apply_hh#batch) vce(cluster unique_id)`

I have 78,670 observations with about 42000 distinct unique_ids. The FEs in absorb() amount to about 3000 dummies. 

The error I get is `insufficient observations`.
When I remove the vce(cluster) option, the code runs properly. Could you help out with what I must be doing wrong here?

**Comment by toyokuma** [comment]
Same problem occurred. Is there a way to figure it out? @nikhilklath @sergiocorreia Thx.

**Comment by sergiocorreia** [comment]
What do you get if you

a) Run ivreghdfe with the `keepsingleton` option
b) Just run the reduced form or the first stage with reghdfe?

I'm asking this because I suspect you _might_ have insufficient observations if there are a lot of singletons.

**Comment by nikhilklath** [comment]
What I found to work finally was that I unstalled all the packages (`ftools, ivreghdfe, reghdfe, ivreg2`) and reinstalled all of then from `ssc install` and **not** `net install`. My best guess was that the older version worked well and the more recent version had some change that made at least my code to not work.

**Comment by toyokuma** [comment]
uninstall and use `ssc install` to install again works for me too. BTW, I didn't impose `ivreghdfe` to keep singletons obs. @sergiocorreia

**Comment by usewei-cell** [comment]
I also have the same issue when using ivreghdfe with the absorb and cluster options; it reports insufficient observations and no singleton. Furthermore, there is no such issue now that the cluster option has been removed.

**Comment by sergiocorreia** [comment]
Fixed by https://github.com/sergiocorreia/reghdfe/commit/e73880cf55ee6a6d225f35381e0621cc66453adb !
