### ISSUE TITLE
Cannot access r(table)

### ISSUE THREAD

**Issue by bojeryd91** [sergiocorreia/ivreghdfe#45]
I suspect that the use of
`mata: _coef_table()`
on line 2541 isn't working as intended since I cannot access r(table) after estimating my model
https://github.com/sergiocorreia/ivreghdfe/blob/9681fb8398493c1d4fa0fca275219d688a4570b3/src/ivreghdfe.ado#L2541

**Comment by sergiocorreia** [comment]
Hi Jesper,

Sorry for the late reply, I was out on leave. What version of ivreghdfe are you using, and what type of model are you running?

On my end, the command seems to work fine:

```stata
sysuse auto
ivreghdfe price weight (length=gear), a(turn)
return list
matrix t = r(table)
matrix list t
```

**Comment by bojeryd91** [comment]
Hi Sergio,

Thanks for getting back to me. I am also traveling and will have to check
this once I'm back. I had the issue on a server at a central bank where I
intern over the summer.

The model is of that type but uses the cluster option too. Other than that,
your code would be an MWE for me except that I wouldn't have used
"return list".

I should've have noted the version before filing the bug... Anyhow, I'll
write you as soon as I am back in the office.

Thanks,
Jesper

**Comment by bojeryd91** [comment]
Hi again Sergio,

It turns out we are running the first version of ivreghdfe (even though it was added in early 2022). I'll contact the server support with admin rights to update commands. Thanks for taking the time.
