### ISSUE TITLE
Coefficients differ when using absorb with analytic weights

### ISSUE THREAD

**Issue by JamesMaxwellHarrison** [sergiocorreia/ivreghdfe#48]
Coefficients differ when using absorb with analytic weights. The issue is replicated in the code below. The change in coefficients is minor here, but it is nontrivial in the dataset I am using. Thanks!

```
sysuse auto
reghdfe price weight [aweight = mpg], a(turn) // coef = 4.320956
ivreg2 price weight i.turn [aweight = mpg], partial(i.turn) small // coef = 4.320956
ivreghdfe price weight i.turn [aweight = mpg] // coef = 4.320956
ivreghdfe price weight [aweight = mpg], a(turn) // coef = 4.367747
```

**Comment by sergiocorreia** [comment]
Thanks for the report.

Running ivreghdfe with the verbose option shows the problem:

```stata
ivreghdfe price weight [aweight = mpg], a(turn) verbose(2)
```

```
# Passing main options to Mata

    - HDFE.absvars = `"turn"' 
    - HDFE.tousevar = `"__000003"' 
    - HDFE.weight_type = `""' 
    - HDFE.weight_var = `""' 
    - HDFE.technique = `"map"' 
```

So it seems that the info is not being passed on correctly; should be an easy fix over the next hours.

**Comment by JamesMaxwellHarrison** [comment]
Wonderful, thanks for looking into it so quickly!

**Comment by sergiocorreia** [comment]
Should be working now; let me know if you spot anything!
